/**
Name:   ErrorCode.h
Author:  jjuiddong
Date:    3/15/2013


*/
#pragma once

namespace network { namespace error {

	enum ERROR_CODE
	{
		ERR_SUCCESS = 0,
		ERR_NO_ERROR = ERR_SUCCESS,

		// common
		ERR_NOT_FOUND_GROUP,
		ERR_NOT_FOUND_USER,
		ERR_ALREADY_EXIST_USER,

		// group
		ERR_NO_CREATE_GROUP,
		ERR_NOT_JOIN_GROUP,

		// group list
		ERR_GROUPLIST_NOT_FOUND_GROUP,		

		// create group
		ERR_GROUPCREATE_NOT_FOUND_PARENT_GROUP,
		ERR_GROUPCREATE_PARENT_TERMINALNODE,
		ERR_GROUPCREATE_NOR_MORE_CREATE_GROUP,

		// join group
		ERR_GROUPJOIN_ALREADY_SAME_GROUP,
		ERR_GROUPJOIN_NOT_TERMINAL,

		// p2p connect
		ERR_P2PCONNECTION_NO_MEMBER_IN_GROUP,
		ERR_P2PCONNECTION_ALREADY_CONNECTED,
		ERR_P2PCONNECTION_HOSTCLIENT_DISAPPEAR,
		

		// farm  server

		// request server info
		ERR_REQSERVERINFO_NOTFOUND_SERVER,

	};

}}
